---
version: "3"

tasks:
  deps:
    desc: Install dependencies
    cmds:
      - cargo +stable install cargo-llvm-cov --locked

  run:
    desc: Run a binary or example of the local package
    cmds:
      - cargo run

  unit:
    desc: Run the tests
    cmds:
      - cargo test

  test:
    desc: Test all
    cmds:
      - task: fmt:check
      - task: cov

  cov:
    desc: Use LLVM source-based code coverage (-C instrument-coverage).
    cmds:
      - cargo llvm-cov --cobertura --output-path cobertura.xml

  cov:map:
    desc: Generate coverage report in "html" format
    cmds:
      - cargo llvm-cov --html --open

  fmt:
    desc: This utility formats all bin and lib files of the current crate using rustfmt
    cmds:
      - cargo fmt

  fmt:check:
    desc: Run rustfmt in check mode
    cmds:
      - cargo fmt --check

  build:
    desc: Compile the current package
    cmds:
      - cargo build --verbose
